version: '3.8'

services:

  wordpress:
    image: wordpress
    ports:
      - "8080:80"
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 2

  mysql:
    image: mysql:latest
    volumes:
      - db-data:/var/lib/mysql/data
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpress
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure

volumes:
  db-data:

networks:
  overlay: